### PR TITLE
Few important docs added along with curated SPOJ question list and solutions

### PR DESCRIPTION
**Pull request by thedrivingforc**

### CODE REVIEW

**Review by sastava007 — CHANGES_REQUESTED** [review]
@thedrivingforc Can you add all the `.txt/.pdf` and non `.CPP` files into `./library` and also remove any binary file.

**Comment by thedrivingforc** [comment]
i have kept the spoj one in a folder so i think it would be a lot more easier to access,if you say.
and for the rest of .pdf and .txt i am moving it to library

**Review by sastava007 — COMMENTED** [review]
@thedrivingforc 
I'm talking about these files, just move them to `./library`
- Competitive Programming Roadmap.txt
- Cpp STL Reference-Manual.pdf
-  all stl functions.pdf

**Comment by thedrivingforc** [comment]
okay

**Comment by thedrivingforc** [comment]
done the changes.please add hacktoberfest label to it.

**Pull request merged**
